GUI_NAME = "BacklitManager"

PLAYER_ICON_MATCH_THRESHOLD = 0.30
RUNE_ICON_MATCH_THRESHOLD = 0.22
RANDOM_ICON_MATCH_THRESHOLD = 0.22

DEFAULT_BAUDRATE = 115200
DEFAULT_PORT = "COM3"
PAUSE = 0.0
OPEN_DELAY_SECONDS = 0.25
HANDSHAKE_TIMEOUT_SECONDS = 2.0

# Common key bindings
JUMP_KEY = "v"
ROPE_LIFT_KEY = "h"